/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Entity.GIANGVIEN;
import Entity.SinhVien;
import MyPanel.DANGKYMON;
import MyPanel.XEMDIEM;
import MyPanel.pn_CaiDat;
import MyPanel.pn_GiangVien;
import MyPanel.pn_LopHoc;
import MyPanel.pn_LopTinChi;
import MyPanel.pn_MonHoc;
import MyPanel.pn_NhapDiem;
import MyPanel.pn_QuanLyHocPhi;
import MyPanel.pn_SinhVien;
import MyPanel.pn_TaoTaiKhoan;
import java.awt.BorderLayout;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author TRANG TUAN MINH
 */
public class Main extends javax.swing.JFrame {

    private Variables variables;
    private pn_SinhVien pn_SV;
    private pn_GiangVien pn_GV; 
    private pn_LopHoc pn_LH;
    private pn_LopTinChi pn_LTC;
    private pn_MonHoc pn_MH;
    private pn_NhapDiem pn_ND;
    private DANGKYMON pn_DK;
    private XEMDIEM pn_XD;
    private pn_QuanLyHocPhi pn_QLHP;
    private pn_TaoTaiKhoan pn_TTK;

    public Main() throws SQLException {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setResizable(false);
        this.variables = new Variables();
        
        setUpServers();
        
        this.pn_SV = new pn_SinhVien(this.variables);
        this.pn_SinhVien.add(pn_SV, BorderLayout.CENTER);
        this.pn_GV = new pn_GiangVien(this.variables);
        this.pn_GiangVien.add(pn_GV, BorderLayout.CENTER);
        this.pn_LH = new pn_LopHoc(this.variables);
        this.pn_LopHoc.add(pn_LH, BorderLayout.CENTER);
        this.pn_LTC = new pn_LopTinChi(this.variables);
        this.pn_LopTinChi.add(pn_LTC, BorderLayout.CENTER);
        this.pn_MH = new pn_MonHoc(this.variables);
        this.pn_MonHoc.add(pn_MH, BorderLayout.CENTER);
        this.pn_ND = new pn_NhapDiem(this.variables);
        this.pn_NhapDiem.add(pn_ND, BorderLayout.CENTER);
        TP_App.setVisible(false);
        
        this.pn_DK = new DANGKYMON(this.variables);
        this.pn_dangKyMon.add(pn_DK, BorderLayout.CENTER);
        this.pn_XD = new XEMDIEM(this.variables);
        this.pn_xemDiem.add(pn_XD, BorderLayout.CENTER);
        TP_SinhVien.setVisible(false);
        
        this.pn_QLHP = new pn_QuanLyHocPhi(this.variables);
        this.pn_QuanLyHocPhi.add(pn_QLHP, BorderLayout.CENTER);
        this.pn_TTK = new pn_TaoTaiKhoan(this.variables);
        this.pn_TaoTaiKhoan.add(pn_TTK, BorderLayout.CENTER);
        TP_PKT.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Login = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txt_login_username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pass_login_password = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        cb_login_faculty = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btn_login_exit = new javax.swing.JButton();
        btn_login_submit = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        TP_App = new javax.swing.JTabbedPane();
        pn_GiangVien = new javax.swing.JPanel();
        pn_SinhVien = new javax.swing.JPanel();
        pn_LopHoc = new javax.swing.JPanel();
        pn_LopTinChi = new javax.swing.JPanel();
        pn_MonHoc = new javax.swing.JPanel();
        pn_NhapDiem = new javax.swing.JPanel();
        pn_CaiDat = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_CaiDat_Logout = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        lbl_currentUserName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        lbl_currentUserDepartment = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TP_SinhVien = new javax.swing.JTabbedPane();
        pn_dangKyMon = new javax.swing.JPanel();
        pn_xemDiem = new javax.swing.JPanel();
        pn_CaiDat1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        btn_CaiDat_Logout1 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        lbl_currentUserName1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        lbl_currentUserDepartment1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TP_PKT = new javax.swing.JTabbedPane();
        pn_QuanLyHocPhi = new javax.swing.JPanel();
        pn_TaoTaiKhoan = new javax.swing.JPanel();
        pn_CaiDat2 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        btn_CaiDat_Logout2 = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        lbl_currentUserName2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        lbl_currentUserDepartment2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sinh viên hệ tín chỉ");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("QUẢN LÝ SINH VIÊN HỆ TÍN CHỈ");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel9.setLayout(new java.awt.BorderLayout(0, 40));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đăng nhập");
        jPanel9.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(4, 1));

        txt_login_username.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Tên đăng nhập");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_login_username, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_login_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jPanel3.add(jPanel2);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Mật khẩu");

        pass_login_password.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(pass_login_password, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pass_login_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4);

        cb_login_faculty.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cb_login_faculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khoa CNTT", "Khoa VT", "Kế Toán" }));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Khoa");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(cb_login_faculty, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_login_faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.add(jPanel5);

        btn_login_exit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_login_exit.setText("Thoát");
        jPanel10.add(btn_login_exit);

        btn_login_submit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_login_submit.setText("Đăng nhập");
        btn_login_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login_submitActionPerformed(evt);
            }
        });
        jPanel10.add(btn_login_submit);

        jPanel3.add(jPanel10);

        jPanel8.add(jPanel3);

        jPanel9.add(jPanel8, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1003, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pn_LoginLayout = new javax.swing.GroupLayout(pn_Login);
        pn_Login.setLayout(pn_LoginLayout);
        pn_LoginLayout.setHorizontalGroup(
            pn_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LoginLayout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_LoginLayout.setVerticalGroup(
            pn_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TP_App.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TP_App.setPreferredSize(new java.awt.Dimension(100, 200));

        pn_GiangVien.setLayout(new java.awt.BorderLayout());
        TP_App.addTab("Giảng Viên", pn_GiangVien);

        pn_SinhVien.setLayout(new java.awt.BorderLayout());
        TP_App.addTab("Sinh Viên", pn_SinhVien);

        pn_LopHoc.setLayout(new java.awt.BorderLayout());
        TP_App.addTab("Lớp Học", pn_LopHoc);

        pn_LopTinChi.setLayout(new java.awt.BorderLayout());
        TP_App.addTab("Lớp Tín Chỉ", pn_LopTinChi);

        pn_MonHoc.setLayout(new java.awt.BorderLayout());
        TP_App.addTab("Môn Học", pn_MonHoc);

        pn_NhapDiem.setLayout(new java.awt.BorderLayout());
        TP_App.addTab("Nhập Điểm", pn_NhapDiem);

        pn_CaiDat.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        btn_CaiDat_Logout.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_CaiDat_Logout.setText("Đăng xuất");
        btn_CaiDat_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CaiDat_LogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btn_CaiDat_Logout);

        lbl_currentUserName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_currentUserName.setText("Tên giảng viên");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Giảng viên");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 694, Short.MAX_VALUE)
                .addComponent(lbl_currentUserName)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbl_currentUserName))
                .addContainerGap())
        );

        lbl_currentUserDepartment.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_currentUserDepartment.setText("Tên chức vụ");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Phòng ban");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_currentUserDepartment)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lbl_currentUserDepartment))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.add(jPanel12);

        pn_CaiDat.add(jPanel6);

        TP_App.addTab("Cài Đặt", pn_CaiDat);

        TP_SinhVien.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        pn_dangKyMon.setLayout(new java.awt.BorderLayout());
        TP_SinhVien.addTab("Đăng ký môn", pn_dangKyMon);

        pn_xemDiem.setLayout(new java.awt.BorderLayout());
        TP_SinhVien.addTab("Xem điểm", pn_xemDiem);

        pn_CaiDat1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        btn_CaiDat_Logout1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_CaiDat_Logout1.setText("Đăng xuất");
        btn_CaiDat_Logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CaiDat_Logout1ActionPerformed(evt);
            }
        });
        jPanel17.add(btn_CaiDat_Logout1);

        lbl_currentUserName1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_currentUserName1.setText("Tên giảng viên");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Sinh viên");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 899, Short.MAX_VALUE)
                .addComponent(lbl_currentUserName1)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_currentUserName1))
                .addContainerGap())
        );

        lbl_currentUserDepartment1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_currentUserDepartment1.setText("Tên chức vụ");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Phòng ban");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_currentUserDepartment1)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lbl_currentUserDepartment1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.add(jPanel16);

        pn_CaiDat1.add(jPanel7);

        TP_SinhVien.addTab("Cài Đặt", pn_CaiDat1);

        TP_PKT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        pn_QuanLyHocPhi.setLayout(new java.awt.BorderLayout());
        TP_PKT.addTab("Quản lý học phí", pn_QuanLyHocPhi);

        pn_TaoTaiKhoan.setLayout(new java.awt.BorderLayout());
        TP_PKT.addTab("Tạo tài khoản", pn_TaoTaiKhoan);

        pn_CaiDat2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel20.setLayout(new java.awt.GridLayout(1, 0));

        btn_CaiDat_Logout2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_CaiDat_Logout2.setText("Đăng xuất");
        btn_CaiDat_Logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CaiDat_Logout2ActionPerformed(evt);
            }
        });
        jPanel22.add(btn_CaiDat_Logout2);

        lbl_currentUserName2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_currentUserName2.setText("Tên giảng viên");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Nhân viên");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 699, Short.MAX_VALUE)
                .addComponent(lbl_currentUserName2)
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbl_currentUserName2))
                .addContainerGap())
        );

        lbl_currentUserDepartment2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbl_currentUserDepartment2.setText("Tên chức vụ");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Phòng ban");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_currentUserDepartment2)
                .addContainerGap())
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lbl_currentUserDepartment2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel20.add(jPanel21);

        pn_CaiDat2.add(jPanel20);

        TP_PKT.addTab("Cài Đặt", pn_CaiDat2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TP_App, javax.swing.GroupLayout.DEFAULT_SIZE, 1104, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TP_SinhVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1104, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TP_PKT, javax.swing.GroupLayout.DEFAULT_SIZE, 1104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pn_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TP_App, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TP_SinhVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(TP_PKT, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
        );

        TP_App.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_login_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login_submitActionPerformed
        String username = txt_login_username.getText();
        String password = pass_login_password.getText();
        String selectedItem = cb_login_faculty.getSelectedItem().toString();

        try {
            this.variables.getDatabase().connectingToSQLServer(selectedItem, username, password);
            String currentUserName = this.variables.getDatabase().getConnection().getMetaData().getUserName();
            String userInfo = "{call sp_dbRolesUsersMap ('%', '" + currentUserName + "')}";
            CallableStatement stmt = this.variables.getDatabase().getConnection().prepareCall(userInfo);
            boolean isSuccess = stmt.execute();
            if (isSuccess){
                ResultSet rs = stmt.getResultSet();
                while(rs.next()){
                    this.variables.getUser().setUsername(currentUserName);
                    this.variables.getUser().setMaGV(rs.getString("Database_User_Name"));
                    this.variables.getUser().setDatabaseRole(rs.getString("DB_Role"));
                }
                
                
                GIANGVIEN gv = new GIANGVIEN();
                SinhVien sv = new SinhVien();
                if (this.variables.getUser().getDatabaseRole().equals(this.variables.getSINH_VIEN())) {
                    this.variables.getUser().setMaGV(username);
                    String query = "EXEC QLDSV_TC.DBO.SP_TimSV '" + username + "'";
                    Statement statement = this.variables.getDatabase().getStatement();
                    ResultSet rs3 = statement.executeQuery(query);
                    while(rs3.next()) {
                        sv.setMaSV(rs3.getString("MASV"));
                        sv.setHo(rs3.getString("HO"));
                        sv.setTen(rs3.getString("TEN"));
                        sv.setPhai(rs3.getInt("PHAI"));
                        sv.setDiaChi(rs3.getString("DIACHI"));
                        sv.setNgaySinh(rs3.getDate("NGAYSINH").toLocalDate());
                        sv.setDaNghiHoc(rs3.getInt("DANGHIHOC"));
                        sv.setPassword(rs3.getString("PASSWORD"));
                    }
                } else {
                    String findGiangVien = "{call sp_findGiangVienByMaGV ('" + this.variables.getUser().getMaGV() + "')}";
                    CallableStatement stmt2 = this.variables.getDatabase().getConnection().prepareCall(findGiangVien);
                    boolean isSuccess2 = stmt2.execute();
                    if (isSuccess2) {
                        ResultSet rs2 = stmt2.getResultSet();
                        while(rs2.next()){
                            gv.setMaGV(rs2.getString("MAGV"));
                            gv.setHo(rs2.getString("HO"));
                            gv.setTen(rs2.getString("TEN"));
                            gv.setMaKhoa(rs2.getString("MAKHOA"));
                            gv.setHocVi(rs2.getString("HOCVI"));
                            gv.setHocHam(rs2.getString("HOCHAM"));
                            gv.setChuyenMon(rs2.getString("CHUYENMON"));
                        }
                    }
                }
                if (this.variables.getUser().getDatabaseRole().equals(this.variables.getPHONG_GIAO_VU())
                        || this.variables.getUser().getDatabaseRole().equals(this.variables.getKHOA())) {
                    this.lbl_currentUserName.setText(gv.getHo() + ' ' + gv.getTen());
                    this.lbl_currentUserDepartment.setText(this.variables.getDepartments().get(this.variables.getUser().getDatabaseRole()));
                    pn_Login.setVisible(false);
                    TP_App.setVisible(true);
                    this.variables.getDatabase().loadListGiangVien();
                    this.pn_GV.putDataIntoTable();
                    this.pn_SV.setUpKhoaComboBox();
                    this.pn_LH.setUpKhoaComboBox();
                    this.pn_LTC.setUpKhoaComboBox();
                    this.variables.getDatabase().loadListMonHoc();
                    this.pn_MH.putDataIntoTable();
                    this.variables.getDatabase().loadListDangKy();
                    this.pn_ND.setUpKhoaComboBox();
                } else if (this.variables.getUser().getDatabaseRole().equals(this.variables.getSINH_VIEN())) {
                    this.lbl_currentUserName1.setText(sv.getHo() + ' ' + sv.getTen());
                    this.lbl_currentUserDepartment1.setText(this.variables.getDepartments().get(this.variables.getUser().getDatabaseRole()));
                    this.pn_XD.setUp();
                    this.pn_DK.setUp();
                    pn_Login.setVisible(false);
                    TP_SinhVien.setVisible(true);
                } else if (this.variables.getUser().getDatabaseRole().equals(this.variables.getPHONG_KE_TOAN())){
                    this.lbl_currentUserName2.setText(gv.getHo() + ' ' + gv.getTen());
                    this.lbl_currentUserDepartment2.setText(this.variables.getDepartments().get(this.variables.getUser().getDatabaseRole()));
                    this.pn_TTK.setUpGiangVienCombobox();
                    pn_Login.setVisible(false);
                    TP_PKT.setVisible(true);
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Tài khoản hoặc mật khẩu không chính xác.", "Sai thông tin đăng nhập", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_login_submitActionPerformed

    private void btn_CaiDat_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CaiDat_LogoutActionPerformed
        try {
            Database db = this.variables.getDatabase();
            db.getConnection().close();
            db.clearAllData();
            this.pn_GV.clearAllDataFromTable();
            this.pn_SV.clearAllDataFromTable();
            this.pn_LH.clearAllDataFromTable();
            this.pn_LTC.clearAllDataFromTable();
            this.pn_MH.clearAllDataFromTable();
            this.pn_ND.clearAllDataFromTable();
            pn_Login.setVisible(true);
            TP_App.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(pn_CaiDat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_CaiDat_LogoutActionPerformed

    private void btn_CaiDat_Logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CaiDat_Logout1ActionPerformed
        try {
            Database db = this.variables.getDatabase();
            db.getConnection().close();
            db.clearAllData();
            this.pn_GV.clearAllDataFromTable();
            this.pn_SV.clearAllDataFromTable();
            this.pn_LH.clearAllDataFromTable();
            this.pn_LTC.clearAllDataFromTable();
            this.pn_MH.clearAllDataFromTable();
            this.pn_ND.clearAllDataFromTable();
            pn_Login.setVisible(true);
            TP_SinhVien.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(pn_CaiDat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_CaiDat_Logout1ActionPerformed

    private void btn_CaiDat_Logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CaiDat_Logout2ActionPerformed
        try {
            Database db = this.variables.getDatabase();
            db.getConnection().close();
            db.clearAllData();
            this.pn_GV.clearAllDataFromTable();
            this.pn_SV.clearAllDataFromTable();
            this.pn_LH.clearAllDataFromTable();
            this.pn_LTC.clearAllDataFromTable();
            this.pn_MH.clearAllDataFromTable();
            this.pn_ND.clearAllDataFromTable();
            pn_Login.setVisible(true);
            TP_PKT.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(pn_CaiDat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_CaiDat_Logout2ActionPerformed

    public void setUpServers () {
        cb_login_faculty.removeAllItems();
        Object[] servers = this.variables.getDatabase().getServers().keySet().toArray();
        for(Object item: servers){
            cb_login_faculty.addItem(item.toString());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TP_App;
    private javax.swing.JTabbedPane TP_PKT;
    private javax.swing.JTabbedPane TP_SinhVien;
    private javax.swing.JButton btn_CaiDat_Logout;
    private javax.swing.JButton btn_CaiDat_Logout1;
    private javax.swing.JButton btn_CaiDat_Logout2;
    private javax.swing.JButton btn_login_exit;
    private javax.swing.JButton btn_login_submit;
    private javax.swing.JComboBox<String> cb_login_faculty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbl_currentUserDepartment;
    private javax.swing.JLabel lbl_currentUserDepartment1;
    private javax.swing.JLabel lbl_currentUserDepartment2;
    private javax.swing.JLabel lbl_currentUserName;
    private javax.swing.JLabel lbl_currentUserName1;
    private javax.swing.JLabel lbl_currentUserName2;
    private javax.swing.JPasswordField pass_login_password;
    private javax.swing.JPanel pn_CaiDat;
    private javax.swing.JPanel pn_CaiDat1;
    private javax.swing.JPanel pn_CaiDat2;
    private javax.swing.JPanel pn_GiangVien;
    private javax.swing.JPanel pn_Login;
    private javax.swing.JPanel pn_LopHoc;
    private javax.swing.JPanel pn_LopTinChi;
    private javax.swing.JPanel pn_MonHoc;
    private javax.swing.JPanel pn_NhapDiem;
    private javax.swing.JPanel pn_QuanLyHocPhi;
    private javax.swing.JPanel pn_SinhVien;
    private javax.swing.JPanel pn_TaoTaiKhoan;
    private javax.swing.JPanel pn_dangKyMon;
    private javax.swing.JPanel pn_xemDiem;
    private javax.swing.JTextField txt_login_username;
    // End of variables declaration//GEN-END:variables
}
