/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MyPanel;

import Entity.LOPTINCHI;
import Entity.MONHOC;
import Entity.SinhVien;
import Main.Variables;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ADMIN
 */
public class pn_LopTinChi extends javax.swing.JPanel {
    private Variables variables;
    /**
     * Creates new form pn
     */
    public pn_LopTinChi(Variables variables) {
        initComponents();
        this.variables = variables;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_LopTinChi = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        txt_timKiem = new javax.swing.JTextField();
        btn_timKiem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbb_khoa = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbb_nienKhoa = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cbb_hocKy = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_maLTC = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_nienKhoa = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_nhom = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbb_form_hocKy = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbb_form_maMH = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cb_huyLop = new javax.swing.JCheckBox();
        jPanel16 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_maGiangVien = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txt_maKhoa = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txt_soSVTT = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        btn_ghi = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách lớp tín chỉ");
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        tbl_LopTinChi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tbl_LopTinChi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã lớp tín chỉ", "Niên khóa", "Học kỳ", "Mã môn học", "Nhóm", "Mã giảng viên", "Mã khoa", "Số sinh viên tối thiểu", "Hủy lớp"
            }
        ));
        tbl_LopTinChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_LopTinChiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_LopTinChi);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        txt_timKiem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btn_timKiem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_timKiem.setText("Tìm kiếm");
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("KHOA");

        cbb_khoa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cbb_khoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công Nghệ Thông Tin", "Viễn Thông" }));
        cbb_khoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_khoaItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Niên khóa");

        cbb_nienKhoa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cbb_nienKhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công Nghệ Thông Tin", "Viễn Thông" }));
        cbb_nienKhoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_nienKhoaItemStateChanged(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Học kỳ");

        cbb_hocKy.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cbb_hocKy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công Nghệ Thông Tin", "Viễn Thông" }));
        cbb_hocKy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_hocKyItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_timKiem)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbb_khoa, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbb_nienKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbb_hocKy, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(cbb_hocKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(cbb_nienKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cbb_khoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_timKiem)))
                .addContainerGap())
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_timKiem, txt_timKiem});

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Mã lớp tín chỉ");

        txt_maLTC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_maLTC.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(txt_maLTC, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_maLTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Niên khóa");

        txt_nienKhoa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(txt_nienKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_nienKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Nhóm");

        txt_nhom.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(txt_nhom, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nhom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Học kỳ");

        cbb_form_hocKy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbb_form_hocKy, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbb_form_hocKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Mã môn học");

        cbb_form_maMH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbb_form_maMH, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbb_form_maMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Hủy lớp");

        cb_huyLop.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cb_huyLop.setText("Đã hủy");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cb_huyLop)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_huyLop))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Mã giảng viên");

        txt_maGiangVien.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_maGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_maGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Mã khoa");

        txt_maKhoa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_maKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_maKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Số sinh viên tối thiểu");

        txt_soSVTT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(txt_soSVTT, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_soSVTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.CardLayout());

        jButton7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jButton7.setText("Thoát");
        jPanel6.add(jButton7);

        btn_ghi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_ghi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/paper.png"))); // NOI18N
        btn_ghi.setText("Ghi");
        btn_ghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ghiActionPerformed(evt);
            }
        });
        jPanel6.add(btn_ghi);

        jButton3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/undo.png"))); // NOI18N
        jButton3.setText("Phục hồi");
        jPanel6.add(jButton3);

        btn_them.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insert (1).png"))); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel6.add(btn_them);

        btn_refresh.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh.png"))); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jPanel6.add(btn_refresh);

        jPanel1.add(jPanel6, "card2");

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbb_khoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_khoaItemStateChanged
        try {
            setUpNienKhoaCombobox();
            setUpForm();
        } catch (SQLException ex) {
            Logger.getLogger(pn_LopTinChi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbb_khoaItemStateChanged

    private void tbl_LopTinChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_LopTinChiMouseClicked
        int selectedIndex = tbl_LopTinChi.getSelectedRow();
        LOPTINCHI ltc = this.variables.getDatabase().getLopTinChiManager().getListLTC().get(selectedIndex);
        putDataIntoForm(ltc);
    }//GEN-LAST:event_tbl_LopTinChiMouseClicked

    private void cbb_nienKhoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_nienKhoaItemStateChanged
        try {
            setUpHocKyCombobox();
        } catch (SQLException ex) {
            Logger.getLogger(pn_LopTinChi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbb_nienKhoaItemStateChanged

    private void cbb_hocKyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_hocKyItemStateChanged
        try {
            loadLopTinChi();
        } catch (SQLException ex) {
            Logger.getLogger(pn_LopTinChi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbb_hocKyItemStateChanged

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        try {
            setUpForm();
            loadLopTinChi();
        } catch (SQLException ex) {
            Logger.getLogger(pn_LopTinChi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        insertLopTinChi();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_ghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ghiActionPerformed
        int index = tbl_LopTinChi.getSelectedRow();
        LOPTINCHI ltc = this.variables.getDatabase().getLopTinChiManager().getListLTC().get(index);
        editLopTinChi(ltc);
    }//GEN-LAST:event_btn_ghiActionPerformed

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        searchLopTinChi();
    }//GEN-LAST:event_btn_timKiemActionPerformed

    public void setUpForm() throws SQLException {
        if (this.cbb_khoa.getSelectedItem() != null) {
            txt_maLTC.setText("");
            txt_nienKhoa.setText("");
            cbb_form_hocKy.removeAllItems();
            for(int i = 1; i <= 3; i++) {
                cbb_form_hocKy.addItem(String.valueOf(i));
            }
            txt_maGiangVien.setText(this.variables.getUser().getMaGV());
            txt_maGiangVien.setEnabled(false);
            txt_maKhoa.setText(this.cbb_khoa.getSelectedItem().toString().replace("KHOA ", ""));
            txt_maKhoa.setEnabled(false);
            cbb_form_maMH.removeAllItems();
            this.variables.getDatabase().loadListMonHoc();
            List<MONHOC> list = this.variables.getDatabase().getMonHocManager().getListMONHOC();
            for(MONHOC item: list) {
                cbb_form_maMH.addItem(item.getMamh());
            }
            txt_nhom.setText("");
            txt_soSVTT.setText("");
            cb_huyLop.setSelected(false);
        }
    }
    
    public void setUpKhoaComboBox() {
        cbb_khoa.removeAllItems();
        Object[] servers = this.variables.getDatabase().getServers().keySet().toArray();
        
        if(this.variables.getUser().getDatabaseRole().equals("KHOA")) {
            cbb_khoa.addItem(this.variables.getDatabase().getCurrentServerName());
        } else {
            for(Object item: servers){
                if(!item.toString().equals(this.variables.getPHONG_KE_TOAN_NAME())){
                    cbb_khoa.addItem(item.toString());
                }
            }
        }
    }
    
    public void setUpNienKhoaCombobox() throws SQLException{
        if (cbb_khoa.getSelectedItem() != null) {
            String selectedKhoa = cbb_khoa.getSelectedItem().toString();
            String link = this.variables.getLink(this.variables.getDatabase().getCurrentServerName(), selectedKhoa);
            String query = "";
            if (link == null) {
                query = "select * from QLDSV_TC.DBO.view_getNK";
            } else {
                query = "select * from " + link + ".QLDSV_TC.DBO.view_getNK";
            }
            Statement stmt = this.variables.getDatabase().getStatement();
            ResultSet rs = stmt.executeQuery(query);
            List<String> nienKhoa = new ArrayList<>();
            while(rs.next()) {
                nienKhoa.add(rs.getString("NIENKHOA"));
            }
            cbb_nienKhoa.removeAllItems();
            for (String item: nienKhoa){
                cbb_nienKhoa.addItem(item);
            }
        }
    }
    
    public void setUpHocKyCombobox() throws SQLException{
        if (cbb_khoa.getSelectedItem() != null && cbb_nienKhoa.getSelectedItem() != null) {
            String selectedKhoa = cbb_khoa.getSelectedItem().toString();
            String selectedNienKhoa = cbb_nienKhoa.getSelectedItem().toString();
            String link = this.variables.getLink(this.variables.getDatabase().getCurrentServerName(), selectedKhoa);
            String query = "";
            if (link == null) {
                query = "EXEC QLDSV_TC.DBO.SP_GETHK '" + selectedNienKhoa +"'";
            } else {
                query = "EXEC " + link + ".QLDSV_TC.DBO.SP_GETHK '" + selectedNienKhoa +"'";
            }
            Statement stmt = this.variables.getDatabase().getStatement();
            ResultSet rs = stmt.executeQuery(query);
            List<String> hocKy = new ArrayList<>();
            while(rs.next()) {
                hocKy.add(rs.getString("HOCKY"));
            }
            cbb_hocKy.removeAllItems();
            for (String item: hocKy){
                cbb_hocKy.addItem(item);
            }
        }
    }
    
    public void putDataIntoForm(LOPTINCHI ltc) {
        txt_maLTC.setText(String.valueOf(ltc.getMaLTC()));
        txt_nienKhoa.setText(ltc.getNienKhoa());
        cbb_form_hocKy.setSelectedIndex(ltc.getHocKy() - 1);
        cbb_form_maMH.setSelectedItem(ltc.getMaMH());
        txt_nhom.setText(String.valueOf(ltc.getNhom()));
        txt_maGiangVien.setText(ltc.getMaGV());
        txt_maKhoa.setText(ltc.getMaKhoa());
        txt_soSVTT.setText(String.valueOf(ltc.getSoSVTT()));
        cb_huyLop.setSelected(ltc.getHuyLop() == 1);
    }
    
    public void loadLopTinChi() throws SQLException {
        if (cbb_khoa.getSelectedItem() != null && cbb_nienKhoa.getSelectedItem() != null && cbb_hocKy.getSelectedItem() != null) {
            String selectedKhoa = cbb_khoa.getSelectedItem().toString();
            String selectedNienKhoa = cbb_nienKhoa.getSelectedItem().toString();
            String selectedHocKy = cbb_hocKy.getSelectedItem().toString();
            String link = this.variables.getLink(this.variables.getDatabase().getCurrentServerName(), selectedKhoa);
            String query = "";
            if (link == null) {
                query = "EXEC QLDSV_TC.DBO.SP_GETLTC_NK_HK '" + selectedNienKhoa + "', '" + selectedHocKy + "'";
            } else {
                query = "EXEC " + link + ".QLDSV_TC.DBO.SP_GETLTC_NK_HK '" + selectedNienKhoa + "', '" + selectedHocKy + "'";
            }
            
            Statement stmt = this.variables.getDatabase().getStatement();
            ResultSet rs = stmt.executeQuery(query);
            this.variables.getDatabase().getLopTinChiManager().clearData();
            while(rs.next()) {
                LOPTINCHI ltc = new LOPTINCHI();
                ltc.setMaLTC(rs.getInt("MALTC"));
                ltc.setNienKhoa(rs.getString("NIENKHOA"));
                ltc.setHocKy(rs.getInt("HOCKY"));
                ltc.setMaMH(rs.getString("MAMH"));
                ltc.setNhom(rs.getInt("NHOM"));
                ltc.setMaGV(rs.getString("MAGV"));
                ltc.setMaKhoa(rs.getString("MAKHOA"));
                ltc.setSoSVTT(rs.getInt("SOSVTOITHIEU"));
                ltc.setHuyLop(rs.getInt("HUYLOP"));
                this.variables.getDatabase().getLopTinChiManager().insertLTC(ltc);
            }
            this.putDataIntoTable();
        }
    }
    
    public void insertLopTinChi() {
        String nienKhoa = txt_nienKhoa.getText();
        String hocKy = cbb_form_hocKy.getSelectedItem().toString();
        String maMonHoc = cbb_form_maMH.getSelectedItem().toString();
        String nhom = txt_nhom.getText();
        String maGiangVien = txt_maGiangVien.getText();
        String maKhoa = txt_maKhoa.getText();
        String soSVTT = txt_soSVTT.getText();
        
        String selectedKhoa = cbb_khoa.getSelectedItem().toString();
        String link = this.variables.getLink(this.variables.getDatabase().getCurrentServerName(), selectedKhoa);
        String query = "";
        if (link == null) {
            query = "EXEC QLDSV_TC.DBO.SP_THEMLTC '" + maKhoa + "', '" + nienKhoa + "', '" + hocKy + "', '" + maMonHoc + "', '" + nhom + "', '" + maGiangVien + "', '" + soSVTT + "'";
        } else {
            query = "EXEC " + link + ".QLDSV_TC.DBO.SP_THEMLTC '" + maKhoa + "', '" + nienKhoa + "', '" + hocKy + "', '" + maMonHoc + "', '" + nhom + "', '" + maGiangVien + "', '" + soSVTT + "'";
        }
        Statement stmt = this.variables.getDatabase().getStatement();
        try {
            stmt.execute(query);
            loadLopTinChi();
            JOptionPane.showMessageDialog(this, "Thêm lớp tín chỉ thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(pn_LopTinChi.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Thêm lớp tín chỉ thất bại", "Thất bại", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void editLopTinChi(LOPTINCHI ltc) {
        String maLTC = txt_maLTC.getText();
        String nienKhoa = txt_nienKhoa.getText();
        String hocKy = cbb_form_hocKy.getSelectedItem().toString();
        String maMonHoc = cbb_form_maMH.getSelectedItem().toString().trim();
        String nhom = txt_nhom.getText();
        String soSVTT = txt_soSVTT.getText();
        String huyLop = cb_huyLop.isSelected() ? "1" : "0";
        
        String query =  "EXEC LINK0.QLDSV_TC.DBO.SP_CHINHSUALTC " + maLTC + ", '" + nienKhoa + "', " + hocKy + ", '" + maMonHoc + "', " + nhom + ", " + soSVTT + ", " + huyLop + ", " + this.variables.getCHI_PHI_MOT_TIET() + "";
        System.out.println(query);
        Statement stmt = this.variables.getDatabase().getStatement();
        try {
            stmt.execute(query);
            loadLopTinChi();
            JOptionPane.showMessageDialog(this, "Chỉnh sửa lớp tín chỉ thành công", "Thành công", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(pn_LopTinChi.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Chỉnh sửa lớp tín chỉ thất bại", "Thất bại", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void searchLopTinChi() {
        String maLTC = txt_timKiem.getText();
        String query =  "EXEC QLDSV_TC.DBO.SP_TIMLTCTHEOMALTC " + maLTC;
        Statement stmt = this.variables.getDatabase().getStatement();
        try {
            ResultSet rs = stmt.executeQuery(query);
            this.variables.getDatabase().getLopTinChiManager().clearData();
            while(rs.next()) {
                LOPTINCHI ltc = new LOPTINCHI();
                ltc.setMaLTC(rs.getInt("MALTC"));
                ltc.setNienKhoa(rs.getString("NIENKHOA"));
                ltc.setHocKy(rs.getInt("HOCKY"));
                ltc.setMaMH(rs.getString("MAMH"));
                ltc.setNhom(rs.getInt("NHOM"));
                ltc.setMaGV(rs.getString("MAGV"));
                ltc.setMaKhoa(rs.getString("MAKHOA"));
                ltc.setSoSVTT(rs.getInt("SOSVTOITHIEU"));
                ltc.setHuyLop(rs.getInt("HUYLOP"));
                this.variables.getDatabase().getLopTinChiManager().insertLTC(ltc);
            }
            this.putDataIntoTable();
        } catch (SQLException ex) {
            Logger.getLogger(pn_LopTinChi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void putDataIntoTable() {
        DefaultTableModel classModel = (DefaultTableModel) tbl_LopTinChi.getModel();
        classModel.setRowCount(0);
        List<LOPTINCHI> myList = variables.getDatabase().getLopTinChiManager().getListLTC();
        for (LOPTINCHI item: myList){
            Object[] obj = new Object[]{
                item.getMaLTC(),
                item.getNienKhoa(),
                item.getHocKy(),
                item.getMaMH(),
                item.getNhom(),
                item.getMaGV(),
                item.getMaKhoa(),
                item.getSoSVTT(),
                item.getHuyLop(),
            };
            classModel.addRow(obj);
        }
        sortTable();
    }
    
    private void sortTable() {
        DefaultTableModel teacherModel = (DefaultTableModel) tbl_LopTinChi.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(teacherModel);
        tbl_LopTinChi.setRowSorter(sorter);
    }
    
    public void clearAllDataFromTable() {
        DefaultTableModel subjectModel = (DefaultTableModel) tbl_LopTinChi.getModel();
        subjectModel.setRowCount(0);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ghi;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JCheckBox cb_huyLop;
    private javax.swing.JComboBox<String> cbb_form_hocKy;
    private javax.swing.JComboBox<String> cbb_form_maMH;
    private javax.swing.JComboBox<String> cbb_hocKy;
    private javax.swing.JComboBox<String> cbb_khoa;
    private javax.swing.JComboBox<String> cbb_nienKhoa;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_LopTinChi;
    private javax.swing.JTextField txt_maGiangVien;
    private javax.swing.JTextField txt_maKhoa;
    private javax.swing.JTextField txt_maLTC;
    private javax.swing.JTextField txt_nhom;
    private javax.swing.JTextField txt_nienKhoa;
    private javax.swing.JTextField txt_soSVTT;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables
}
