/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MyPanel;

import Entity.LOP;
import Entity.SinhVien;
import Entity.SinhVienManager;
import Main.Variables;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author TRANG TUAN MINH
 */
public class pn_SinhVien extends javax.swing.JPanel {
    private Variables variables;
    private DefaultTableModel model;
    public pn_SinhVien(Variables variables) {
        initComponents();
        initTableDanhSachSinhVien();
        this.variables = variables;
        clearForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_group_gender = new javax.swing.ButtonGroup();
        btn_group_daNghiHoc = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnGhi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnPhucHoi = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSinhvien = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbb_khoa_form = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cbb_lop_form = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_mssv = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_ho = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        rb_nu = new javax.swing.JRadioButton();
        rb_nam = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_diaChi = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        dc_ngaysinh = new com.toedter.calendar.JDateChooser();
        jPanel16 = new javax.swing.JPanel();
        rb_daNghi = new javax.swing.JRadioButton();
        rb_conHoc = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pass_password = new javax.swing.JPasswordField();
        jPanel12 = new javax.swing.JPanel();
        cbb_khoa = new javax.swing.JComboBox<>();
        txt_timKiem = new javax.swing.JTextField();
        btn_timKiem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbb_lop = new javax.swing.JComboBox<>();

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DANH SÁCH SINH VIÊN");
        jPanel2.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.CardLayout());

        btnGhi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnGhi.setText("Ghi");
        btnGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiActionPerformed(evt);
            }
        });
        jPanel11.add(btnGhi);

        btnXoa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel11.add(btnXoa);

        btnThem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel11.add(btnThem);

        btn_refresh.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        jPanel11.add(btn_refresh);

        btnThoat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnThoat.setText("Thoát");
        jPanel11.add(btnThoat);

        btnPhucHoi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnPhucHoi.setText("Phục Hồi");
        jPanel11.add(btnPhucHoi);

        jPanel4.add(jPanel11, "card2");

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        tblSinhvien.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        tblSinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSinhvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSinhvien);

        jPanel3.setLayout(new java.awt.GridLayout(10, 1));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("KHOA");

        cbb_khoa_form.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cbb_khoa_form.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbb_khoa_form.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_khoa_formItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(cbb_khoa_form, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbb_khoa_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.add(jPanel5);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("LỚP");

        cbb_lop_form.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cbb_lop_form.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(cbb_lop_form, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbb_lop_form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.add(jPanel13);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("MSSV:");

        txt_mssv.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(txt_mssv, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mssv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, txt_mssv});

        jPanel3.add(jPanel1);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("HỌ:");

        txt_ho.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(txt_ho, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_ho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, txt_ho});

        jPanel3.add(jPanel6);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("TÊN:");

        txt_ten.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel4, txt_ten});

        jPanel3.add(jPanel8);

        btn_group_gender.add(rb_nu);
        rb_nu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rb_nu.setText("NỮ");

        btn_group_gender.add(rb_nam);
        rb_nam.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rb_nam.setText("NAM");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("PHÁI:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rb_nam)
                .addGap(18, 18, 18)
                .addComponent(rb_nu)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rb_nam)
                    .addComponent(rb_nu))
                .addContainerGap())
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel5, rb_nam, rb_nu});

        jPanel3.add(jPanel9);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("ĐỊA CHỈ");

        txt_diaChi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(txt_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.add(jPanel15);

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("NGÀY SINH:");

        dc_ngaysinh.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(dc_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dc_ngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel14);

        btn_group_daNghiHoc.add(rb_daNghi);
        rb_daNghi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rb_daNghi.setText("Đã nghỉ");

        btn_group_daNghiHoc.add(rb_conHoc);
        rb_conHoc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rb_conHoc.setText("Còn học");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("ĐÃ NGHỈ HỌC");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rb_conHoc)
                .addGap(18, 18, 18)
                .addComponent(rb_daNghi)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rb_conHoc)
                    .addComponent(rb_daNghi))
                .addContainerGap())
        );

        jPanel3.add(jPanel16);

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("PASSWORD");

        pass_password.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pass_password.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(pass_password, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(pass_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.add(jPanel17);

        cbb_khoa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cbb_khoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công Nghệ Thông Tin", "Viễn Thông" }));
        cbb_khoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_khoaItemStateChanged(evt);
            }
        });

        txt_timKiem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btn_timKiem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_timKiem.setText("Tìm kiếm");
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Khoa");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Lớp");

        cbb_lop.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cbb_lop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công Nghệ Thông Tin", "Viễn Thông" }));
        cbb_lop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_lopItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_timKiem)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbb_khoa, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbb_lop, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(440, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(cbb_lop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_timKiem)
                        .addComponent(jLabel8)
                        .addComponent(cbb_khoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(jPanel10, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        try {
            searchSinhVien();
        } catch (SQLException ex) {
            Logger.getLogger(pn_SinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void cbb_khoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_khoaItemStateChanged
        try {
            setUpLopComboBox(cbb_khoa, cbb_lop);
        } catch (SQLException ex) {
            Logger.getLogger(pn_SinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbb_khoaItemStateChanged

    private void cbb_lopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_lopItemStateChanged
        try {
            loadSinhVien();
        } catch (SQLException ex) {
            Logger.getLogger(pn_SinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbb_lopItemStateChanged

    private void tblSinhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSinhvienMouseClicked
        int index = tblSinhvien.getSelectedRow();
        SinhVien sv = this.variables.getDatabase().getSinhVienManager().getListSinhVien().get(index);
        putDataIntoForm(sv);
    }//GEN-LAST:event_tblSinhvienMouseClicked

    private void cbb_khoa_formItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_khoa_formItemStateChanged
        try {
            setUpLopComboBox(cbb_khoa_form, cbb_lop_form);
        } catch (SQLException ex) {
            Logger.getLogger(pn_SinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbb_khoa_formItemStateChanged

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        insertSinhVien();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiActionPerformed
        editSinhVien();
    }//GEN-LAST:event_btnGhiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        deleteSinhVien();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        try {
            loadSinhVien();
        } catch (SQLException ex) {
            Logger.getLogger(pn_SinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_refreshActionPerformed

    public void setUpKhoaComboBox() {
        cbb_khoa.removeAllItems();
        cbb_khoa_form.removeAllItems();
        Object[] servers = this.variables.getDatabase().getServers().keySet().toArray();
        
        if(this.variables.getUser().getDatabaseRole().equals("KHOA")) {
            cbb_khoa.addItem(this.variables.getDatabase().getCurrentServerName());
            cbb_khoa_form.addItem(this.variables.getDatabase().getCurrentServerName());
        } else {
            for(Object item: servers){
                if(!item.toString().equals(this.variables.getPHONG_KE_TOAN_NAME())){
                    cbb_khoa.addItem(item.toString());
                }
            }

            for(Object item: servers){
                if(!item.toString().equals(this.variables.getPHONG_KE_TOAN_NAME())){
                    cbb_khoa_form.addItem(item.toString());
                }
            }
        }
    }
    
    public void setUpLopComboBox(JComboBox cbb_khoa, JComboBox cbb_lop) throws SQLException {
        if (cbb_khoa.getSelectedItem() != null) {
            String selectedKhoa = cbb_khoa.getSelectedItem().toString();
            String link = this.variables.getLink(this.variables.getDatabase().getCurrentServerName(), selectedKhoa);
            String query = "";
            if (link == null) {
                query = "select * from QLDSV_TC.DBO.view_getAllLop";
                
            } else {
                query = "select * from " + link + ".QLDSV_TC.DBO.view_getAllLop";
            }
            Statement stmt = this.variables.getDatabase().getStatement();
            ResultSet rs = stmt.executeQuery(query);
            this.variables.getDatabase().getLopManager().clearData();
            while(rs.next()) {
                LOP l = new LOP();
                l.setMaLop(rs.getString("MALOP"));
                l.setTenLop(rs.getString("TENLOP"));
                l.setKhoaHoc(rs.getString("KHOAHOC"));
                l.setMaKhoa(rs.getString("MAKHOA"));
                this.variables.getDatabase().getLopManager().insertLOP(l);
            }
            cbb_lop.removeAllItems();
            for (LOP item: this.variables.getDatabase().getLopManager().getListLOP()){
                cbb_lop.addItem(item.getMaLop() + "- " + item.getTenLop());
            }
        }
    }
    
    public void loadSinhVien() throws SQLException {
        if (cbb_khoa.getSelectedItem() != null && cbb_lop.getSelectedItem() != null) {
            String selectedKhoa = cbb_khoa.getSelectedItem().toString();
            String selectedLop = cbb_lop.getSelectedItem().toString();
            String selectedMaLop = selectedLop.substring(0, selectedLop.lastIndexOf("-"));
            
            String link = this.variables.getLink(this.variables.getDatabase().getCurrentServerName(), selectedKhoa);
            String query = "";
            if (link == null) {
                query = "EXEC QLDSV_TC.DBO.SP_TIMSVTHEOMALOP '"+ selectedMaLop +"'";
            } else {
                query = "EXEC " + link + ".QLDSV_TC.DBO.SP_TIMSVTHEOMALOP'"+ selectedMaLop +"'";
            }
            
            Statement stmt = this.variables.getDatabase().getStatement();
            ResultSet rs = stmt.executeQuery(query);
            this.variables.getDatabase().getSinhVienManager().clearData();
            while(rs.next()) {
                if (rs.getInt("DANGHIHOC") == this.variables.getCHUA_NGHI_HOC()) {
                    SinhVien sv = new SinhVien();
                    sv.setMaSV(rs.getString("MASV"));
                    sv.setHo(rs.getString("HO"));
                    sv.setTen(rs.getString("TEN"));
                    sv.setPhai(rs.getInt("PHAI"));
                    sv.setDiaChi(rs.getString("DIACHI"));
                    sv.setNgaySinh(rs.getDate("NGAYSINH").toLocalDate());
                    sv.setMaLop(rs.getString("MALOP"));
                    sv.setDaNghiHoc(rs.getInt("DANGHIHOC"));
                    sv.setPassword(rs.getString("PASSWORD"));
                    this.variables.getDatabase().getSinhVienManager().insertSinhVien(sv);
                }
            }
            this.putDataIntoTable();
        }
    }
    
    public void insertSinhVien() {
        String lop = cbb_lop_form.getSelectedItem().toString();
        String maLop = lop.substring(0, lop.lastIndexOf(" - "));
        String mssv = txt_mssv.getText();
        String ho = txt_ho.getText();
        String ten = txt_ten.getText();
        int phai = rb_nam.isSelected() ? this.variables.getMALE() : this.variables.getFEMALE();
        String diaChi = txt_diaChi.getText();
        LocalDate ngaySinh = dc_ngaysinh.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        int daNghiHoc = rb_conHoc.isSelected() ? this.variables.getCHUA_NGHI_HOC() : this.variables.getDA_NGHI_HOC();
        String password = new String(pass_password.getPassword());
        
        String khoa = cbb_khoa_form.getSelectedItem().toString();
        String link = this.variables.getLink(this.variables.getDatabase().getCurrentServerName(), khoa);
        String query = "";
        if (link == null) {
            query = "EXEC QLDSV_TC.DBO.SP_THEMSV '" + maLop +"', '" + mssv + "', N'" + ho + "', N'" + ten + "', " + phai + ", N'" + diaChi + "', '" + ngaySinh.format(this.variables.getSQL_DATE_TIME_FORMATTER()) + "', " + daNghiHoc + ", '" + password + "'";
        } else {
            query = "EXEC " + link + ".QLDSV_TC.DBO.SP_THEMSV '" + maLop +"', '" + mssv + "', N'" + ho + "', N'" + ten + "', " + phai + ", N'" + diaChi + "', '" + ngaySinh.format(this.variables.getSQL_DATE_TIME_FORMATTER()) + "', " + daNghiHoc + ", '" + password + "'";
        }
        Statement stmt = this.variables.getDatabase().getStatement();
        
        try {
            stmt.execute(query);
            clearForm();
            
            if (!cbb_lop.getSelectedItem().toString().equals(cbb_lop_form.getSelectedItem().toString())){
                cbb_khoa.setSelectedItem(cbb_khoa_form.getSelectedItem());
                cbb_lop.setSelectedItem(cbb_lop_form.getSelectedItem());
            } else {
                loadSinhVien();
            }
            
            JOptionPane.showMessageDialog(this, "Thêm sinh viên thành công", "Thêm thành công", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(pn_SinhVien.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Thêm sinh viên thất bại", "Thêm thất bại", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void editSinhVien() {
        String mssv = txt_mssv.getText();
        String ho = txt_ho.getText();
        String ten = txt_ten.getText();
        int phai = rb_nam.isSelected() ? this.variables.getMALE() : this.variables.getFEMALE();
        String diaChi = txt_diaChi.getText();
        LocalDate ngaySinh = dc_ngaysinh.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        String password = new String(pass_password.getPassword());
        
        String khoa = cbb_khoa_form.getSelectedItem().toString();
        String link = this.variables.getLink(this.variables.getDatabase().getCurrentServerName(), khoa);
        String query = "";
        if (link == null) {
            query = "EXEC QLDSV_TC.DBO.SP_CHINHSUASV '" + mssv + "', N'" + ho + "', N'" + ten + "', " + phai + ", N'" + diaChi + "', '" + ngaySinh + "', '" + password + "'";
        } else {
            query = "EXEC " + link + ".QLDSV_TC.DBO.SP_CHINHSUASV '" + mssv + "', N'" + ho + "', N'" + ten + "', " + phai + ", N'" + diaChi + "', '" + ngaySinh + "', '" + password + "'";
        }
        Statement stmt = this.variables.getDatabase().getStatement();
        
        try {
            stmt.execute(query);
            clearForm();
            
            if (!cbb_lop.getSelectedItem().toString().equals(cbb_lop_form.getSelectedItem().toString())){
                cbb_khoa.setSelectedItem(cbb_khoa_form.getSelectedItem());
                cbb_lop.setSelectedItem(cbb_lop_form.getSelectedItem());
            } else {
                loadSinhVien();
            }
            
            JOptionPane.showMessageDialog(this, "Chỉnh sửa sinh viên thành công", "Thêm thành công", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(pn_SinhVien.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Chỉnh sửa sinh viên thất bại", "Thêm thất bại", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void deleteSinhVien() {
        int confirm = JOptionPane.showConfirmDialog(this, "Xóa sinh viên này?", "Xóa sinh viên", JOptionPane.WARNING_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            int index = tblSinhvien.getSelectedRow();
            SinhVien sv = this.variables.getDatabase().getSinhVienManager().getListSinhVien().get(index);
            String khoa = cbb_khoa_form.getSelectedItem().toString();
            String link = this.variables.getLink(this.variables.getDatabase().getCurrentServerName(), khoa);
            String query = "";
            if (link == null) {
                query = "EXEC QLDSV_TC.DBO.SP_XOASINHVIEN '"+ sv.getMaSV() +"'";
            } else {
                query = "EXEC " + link + ".QLDSV_TC.DBO.SP_XOASINHVIEN '"+ sv.getMaSV() +"'";
            }
            Statement stmt = this.variables.getDatabase().getStatement();
            try {
                stmt.execute(query);
                clearForm();

                if (!cbb_lop.getSelectedItem().toString().equals(cbb_lop_form.getSelectedItem().toString())){
                    cbb_khoa.setSelectedItem(cbb_khoa_form.getSelectedItem());
                    cbb_lop.setSelectedItem(cbb_lop_form.getSelectedItem());
                } else {
                    loadSinhVien();
                }

                JOptionPane.showMessageDialog(this, "Xóa sinh viên thành công", "Xóa thành công", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException ex) {
                Logger.getLogger(pn_SinhVien.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Xóa sinh viên thất bại", "Xóa thất bại", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    public void searchSinhVien() throws SQLException {
        SinhVien sv = new SinhVien();
        String maKhoa = "";
        String maLop = "";
        String mssv = txt_timKiem.getText();
        String query = "EXEC QLDSV_TC.DBO.SP_TimSV '" + mssv + "'";
        Statement statement = this.variables.getDatabase().getStatement();
        ResultSet rs = statement.executeQuery(query);
        while(rs.next()) {
            maKhoa = rs.getString("MAKHOA");
            maLop = rs.getString("MALOP");
            sv.setMaSV(rs.getString("MASV"));
            sv.setHo(rs.getString("HO"));
            sv.setTen(rs.getString("TEN"));
            sv.setPhai(rs.getInt("PHAI"));
            sv.setDiaChi(rs.getString("DIACHI"));
            sv.setNgaySinh(rs.getDate("NGAYSINH").toLocalDate());
            sv.setDaNghiHoc(rs.getInt("DANGHIHOC"));
            sv.setPassword(rs.getString("PASSWORD"));
            sv.setMaLop(maLop);
        }
        
        int cbb_khoa_form_item_count = cbb_khoa.getItemCount();
        for (int i = 0; i < cbb_khoa_form_item_count; i++) {
            if (cbb_khoa.getItemAt(i).contains(maKhoa.trim())) {
                cbb_khoa.setSelectedIndex(i);
            }
        }

        int cbb_lop_form_item_count = cbb_lop.getItemCount();
        for (int i = 0; i < cbb_lop_form_item_count; i++) {
            if (cbb_lop.getItemAt(i).contains(maLop.trim())) {
                cbb_lop.setSelectedIndex(i);
            }
        }
        
        SinhVienManager sinhVienManager = this.variables.getDatabase().getSinhVienManager();
        sinhVienManager.clearData();
        sinhVienManager.insertSinhVien(sv);
        putDataIntoTable();
    }
    
    public void putDataIntoTable() {
        DefaultTableModel studentModel = (DefaultTableModel) tblSinhvien.getModel();
        studentModel.setRowCount(0);
        List<SinhVien> myList = variables.getDatabase().getSinhVienManager().getListSinhVien();
        for (SinhVien item: myList){
            if (item.getDaNghiHoc() == this.variables.getCHUA_NGHI_HOC()){
                Object[] obj = new Object[]{
                    item.getMaSV(),
                    item.getHo(),
                    item.getTen(),
                    item.getPhai() == this.variables.getMALE() ? this.variables.getTEXT_MALE() : this.variables.getTEXT_FEMALE(),
                    item.getDiaChi(),
                    item.getNgaySinh()
                };
                studentModel.addRow(obj);
            }
        }
        sortTable();
    }
    
    public void putDataIntoForm(SinhVien sv){
        LOP lop = this.variables.getDatabase().getLopManager().searchByMaLOP(sv.getMaLop());
        if (lop != null) {
            String maKhoa = lop.getMaKhoa();
            int cbb_khoa_form_item_count = cbb_khoa_form.getItemCount();
            for (int i = 0; i < cbb_khoa_form_item_count; i++) {
                if (cbb_khoa_form.getItemAt(i).contains(maKhoa.trim())) {
                    cbb_khoa_form.setSelectedIndex(i);
                }
            }
            
            int cbb_lop_form_item_count = cbb_lop_form.getItemCount();
            for (int i = 0; i < cbb_lop_form_item_count; i++) {
                if (cbb_lop_form.getItemAt(i).contains(sv.getMaLop().trim())) {
                    cbb_lop_form.setSelectedIndex(i);
                }
            }
            
            txt_mssv.setText(sv.getMaSV());
            txt_ho.setText(sv.getHo());
            txt_ten.setText(sv.getTen());
            
            if (sv.getPhai() == this.variables.getMALE())
                rb_nam.setSelected(true);
            else 
                rb_nu.setSelected(true);
            
            txt_diaChi.setText(sv.getDiaChi());
            dc_ngaysinh.setDate(Date.from(sv.getNgaySinh().atStartOfDay(ZoneId.systemDefault()).toInstant()));
            
            if (sv.getDaNghiHoc()== this.variables.getCHUA_NGHI_HOC())
                rb_conHoc.setSelected(true);
            else 
                rb_daNghi.setSelected(true);
            
            pass_password.setText(sv.getPassword());
        }
        
    }
    
    private void sortTable() {
        DefaultTableModel teacherModel = (DefaultTableModel) tblSinhvien.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(teacherModel);
        tblSinhvien.setRowSorter(sorter);
    }
    
    public void clearAllDataFromTable() {
        DefaultTableModel subjectModel = (DefaultTableModel) tblSinhvien.getModel();
        subjectModel.setRowCount(0);
    }
    
    public void clearForm() {
        txt_mssv.setText("");
        txt_ho.setText("");
        txt_ten.setText("");
        txt_diaChi.setText("");
        dc_ngaysinh.setDate(null);
        pass_password.setText("");
        rb_nam.setSelected(true);
        rb_conHoc.setSelected(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnPhucHoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup btn_group_daNghiHoc;
    private javax.swing.ButtonGroup btn_group_gender;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JComboBox<String> cbb_khoa;
    private javax.swing.JComboBox<String> cbb_khoa_form;
    private javax.swing.JComboBox<String> cbb_lop;
    private javax.swing.JComboBox<String> cbb_lop_form;
    private com.toedter.calendar.JDateChooser dc_ngaysinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField pass_password;
    private javax.swing.JRadioButton rb_conHoc;
    private javax.swing.JRadioButton rb_daNghi;
    private javax.swing.JRadioButton rb_nam;
    private javax.swing.JRadioButton rb_nu;
    private javax.swing.JTable tblSinhvien;
    private javax.swing.JTextField txt_diaChi;
    private javax.swing.JTextField txt_ho;
    private javax.swing.JTextField txt_mssv;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables
     public void initTableDanhSachSinhVien() {
        model = (DefaultTableModel) tblSinhvien.getModel();
        model.setColumnIdentifiers(new Object[] {
                "MSSV" ,"HỌ", "TÊN", "PHÁI","ĐỊA CHỈ","NGÀY SINH"
        });
        model.setRowCount(0);
        
        tblSinhvien.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblSinhvien.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblSinhvien.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblSinhvien.getColumnModel().getColumn(2).setPreferredWidth(200);
        tblSinhvien.getColumnModel().getColumn(3).setPreferredWidth(200);
        tblSinhvien.getColumnModel().getColumn(4).setPreferredWidth(200);
        tblSinhvien.getColumnModel().getColumn(5).setPreferredWidth(200);
    }
}
